<h4><?php //echo $this->__('Module List') ?></h4>

<style type="text/css">
    div.supcard {
        height: 50%;
        width: 50%;

    }
    img {
        max-width: 100%;
        max-height: 100%;
    }
</style>
<div class="row">
    <div class="leftcolumn">


    </div>
    <div class="leftcolumn">
        <h1></h1>
        <?php
         $collection = $this->getCollection();

//        try
//        {
//            $collection = Mage::getModel('blogpost/blogpost')->getCollection();
//            if(isset($_GET['limit']) && $_GET['limit']!='all')
//            {
//                $collection->setPageSize($_GET['limit']);
//                if(isset($_GET['p']))
//                $collection->setCurPage($_GET['p']);
//            }
//            else if(isset($_GET['p']))
//            {
//                $collection->setPageSize(2);
//                $collection->setCurPage($_GET['p']);
//            }
//            else
//            {
//                $collection->setPageSize(2);
//                $collection->setCurPage(1);
//            }
//
//            $size = $collection->getSize();
//            $cnt = count($collection);
//            $i=0;
//
//        }
//        catch (Exception $e)
//        {
//            var_dump($e->getMessage());
//        }
        if(isset($_GET['id']))
        {
            $collection = Mage::getModel('blogpost/blogpost')->getCollection()
                ->addFieldToFilter('blogpost_id', $_GET['id']);
            foreach ($collection as $item)
            {
                $current_count=$item->getViewCount();

                $current_count++;

                $data=array('view_count'=>$current_count);
                $up=Mage::getModel('blogpost/blogpost')->load($_GET['id'])->addData($data);
                try {
                    $up->setId($_GET['id'])->save();
                   // echo "Data updated successfully.";

                } catch (Exception $e){
                    echo $e->getMessage();
                }

            }





        }

        else
        {
            echo $this->getToolbarHtml();
        }



        ?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <div class="page-title">
            <h1><a href="<?php echo $this->getUrl('blogpost/index/pagination');?>"><?php echo $this->__('Local News Blog Home');
                $i=0;
                ?></a></h1>

        </div>


        <?php


        ?>
        <?php if($collection->getSize()): ?>
        <table>

        <?php foreach ($collection as $item) {
            $i++;

            ?>

            <tr>
                <td>
           <div class="card" id="<?php echo $i?>">

                <h2><?php   echo $item->getTitle();?></h2>
                <h5><?php   echo $item->getCreatedAt();?></h5>
                <div class="supcard">
                    <a href='<?php

                    echo Mage::helper('blogpost/data')->process_url($item->getTitle());
                    ?>'><img src="<?php echo Mage::getBaseUrl('media').DS.$item->getFilename(); ?>"/></a>
                </div>
                <p><?php   echo $item->getContent();?></p>
               </div>
            </td>

        <?php }?>
            </tr>

        </table>
            <script type="text/javascript">decorateTable('my-custom-table');</script>
        <?php
        if(!isset($_GET['id']))
        echo $this->getToolbarHtml();
        ?>
        <?php else: ?>
            <p><?php echo $this->__('The collection is empty.'); ?></p>
        <?php endif ?>



    </div>
    <div class="rightcolumn">
        <div class="card">
            <h2>About Me</h2>
            <div class="card">

            <div class="supcard">
                <img src="http://www.recordere.dk/wp-content/uploads/2018/01/zuck.jpg"/>
                <p>I am the creator of Facebook now learning Magento 1</p>
            </div>
            </div>

        </div>

        <div class="card">
            <h3>Popular Post</h3>
            <?php
            $oCollection = Mage::getModel('blogpost/blogpost')->getCollection()
                ->setOrder('view_count', 'DESC');
            $i=0;
            foreach ($oCollection as $item) {
            $i++;
            if($i==3)break;
//            $oCollection
//                ->getSelect()
//                ->order(array('view_count DESC'))
//                ->limit(10);



            ?>
            <div class="card ">
                <h2><?php   echo $item->getTitle();?></h2>
                <h5><?php   echo $item->getCreatedAt();?></h5>
                <div class="supcard">
                    <a href='<?php  echo Mage::helper('blogpost/data')->process_url($item->getTitle());?>'><img src="<?php echo Mage::getBaseUrl('media').DS.$item->getFilename(); ?>"/></a>
                </div>
            </div>

            <?php }?>
            <!--<div class="card">Image</div><br>
            <div class="card">Image</div><br>
            <div class="card">Image</div>-->
        </div>


    </div>
</div>
<?php



/*
    This shows how to load specific fields from a record in the database.
    1) Note the load(15), this corresponds to saying "select * from table where table_id = 15"
    2) You can then just use the get(fieldname) to pull specific data from the table.
    3) If you have a field named news_id, then it becomes getNewsId, etc.
*/
/*
$news = Mage::getModel('blogpost/blogpost')->load(15);
echo $news->getNewsId();
echo $news->getTitle();
echo $news->getContent();
echo $news->getStatus();

*/

/*
    This shows an alternate way of loading datas from a record using the database the "Magento Way" (using blocks and controller).
     Uncomment blocks in /app/code/local/Namespace/Module/controllers/IndexController.php if you want to use it.

*/
/*
$object = $this->getBlogpost();
echo 'id: '.$object['test_id'].'<br/>';
echo 'title: '.$object['title'].'<br/>';
echo 'content: '.$object['content'].'<br/>';
echo 'status: '.$object['status'].'<br/>';
*/


/*
    This shows how to load multiple rows in a collection and save a change to them.
    1) The setPageSize function will load only 5 records per page and you can set the current Page with the setCurPage function.
    2) The $collection->walk('save') allows you to save everything in the collection after all changes have been made.
*/
/*
$i = 0;

$collection = Mage::getModel('blogpost/blogpost')->getCollection();
$collection->setPageSize(5);
$collection->setCurPage(2);
$size = $collection->getSize();
$cnt = count($collection);
foreach ($collection as $item) {
    $i = $i+1;
    $item->setTitle($i);
    echo $item->getTitle();
}

$collection->walk('save');
*/

/*
    This shows how to load a single record and save a change.
    1) Note the setTitle, this corresponds to the table field name, title, and then you pass it the text to change.
    2) Call the save() function only on a single record.
*/
/*
$object = Mage::getModel('blogpost/blogpost')->load(1);
$object->setTitle('This is a changed title');
$object->save();
*/

?>
<script type="text/javascript">
    jQuery( document ).ready(function() {
        //jQuery(this).animate();
        var total='<?php echo $i?>';
        console.log(total);
       for(x=1;x<=total;x++)
       {
           jQuery('#'+x).hide().delay(500*x).fadeIn(500);
       }
          //  jQuery(this).hide().fadeIn(1000);
        //});


    });
</script>
