<h4><?php //echo $this->__('Module List') ?></h4>


<div class="row">
    <div class="leftcolumn">


    </div>
    <div class="leftcolumn">
        <h1></h1>
        <?php

        try
        {
            $collection = Mage::getModel('blogpost/blogpost')->getCollection();
            if(isset($_GET) && $_GET['limit']!='all')
            {
                $collection->setPageSize($_GET['limit']);
                $collection->setCurPage($_GET['p']);
            }

            $size = $collection->getSize();
            $cnt = count($collection);
            $i=0;

        }
        catch (Exception $e)
        {
            var_dump($e->getMessage());
        }



        ?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>


        <?php echo $this->getToolbarHtml(); ?>
        <?php if($collection->getSize()): ?>
        <table>

        <?php foreach ($collection as $item) {

            ?>

            <tr>
                <td>
           <div class="card">

                <h2><?php   echo $item->getTitle();?></h2>
                <h5><?php   echo $item->getCreatedAt();?></h5>
                <div>
                    <img src="<?php echo Mage::getBaseUrl('media').DS.$item->getFilename(); ?>"/>
                </div>
                <p><?php   echo $item->getContent();?></p>
            </div>
            </td>

        <?php }?>
            </tr>

        </table>
            <script type="text/javascript">decorateTable('my-custom-table');</script>
        <?php echo $this->getToolbarHtml(); ?>
        <?php else: ?>
            <p><?php echo $this->__('The collection is empty.'); ?></p>
        <?php endif ?>



    </div>
    <div class="rightcolumn">
        <div class="card">
            <h2>About Me</h2>
            <div class="fakeimg" style="height:100px;">Image</div>
            <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
        </div>
        <div class="card">
            <h3>Popular Post</h3>
            <div class="fakeimg">Image</div><br>
            <div class="fakeimg">Image</div><br>
            <div class="fakeimg">Image</div>
        </div>
        <div class="card">
            <h3>Follow Me</h3>
            <p>Some text..</p>
        </div>
    </div>
</div>
<?php



/*
    This shows how to load specific fields from a record in the database.
    1) Note the load(15), this corresponds to saying "select * from table where table_id = 15"
    2) You can then just use the get(fieldname) to pull specific data from the table.
    3) If you have a field named news_id, then it becomes getNewsId, etc.
*/
/*
$news = Mage::getModel('blogpost/blogpost')->load(15);
echo $news->getNewsId();
echo $news->getTitle();
echo $news->getContent();
echo $news->getStatus();

*/

/*
    This shows an alternate way of loading datas from a record using the database the "Magento Way" (using blocks and controller).
     Uncomment blocks in /app/code/local/Namespace/Module/controllers/IndexController.php if you want to use it.

*/
/*
$object = $this->getBlogpost();
echo 'id: '.$object['test_id'].'<br/>';
echo 'title: '.$object['title'].'<br/>';
echo 'content: '.$object['content'].'<br/>';
echo 'status: '.$object['status'].'<br/>';
*/


/*
    This shows how to load multiple rows in a collection and save a change to them.
    1) The setPageSize function will load only 5 records per page and you can set the current Page with the setCurPage function.
    2) The $collection->walk('save') allows you to save everything in the collection after all changes have been made.
*/
/*
$i = 0;

$collection = Mage::getModel('blogpost/blogpost')->getCollection();
$collection->setPageSize(5);
$collection->setCurPage(2);
$size = $collection->getSize();
$cnt = count($collection);
foreach ($collection as $item) {
    $i = $i+1;
    $item->setTitle($i);
    echo $item->getTitle();
}

$collection->walk('save');
*/

/*
    This shows how to load a single record and save a change.
    1) Note the setTitle, this corresponds to the table field name, title, and then you pass it the text to change.
    2) Call the save() function only on a single record.
*/
/*
$object = Mage::getModel('blogpost/blogpost')->load(1);
$object->setTitle('This is a changed title');
$object->save();
*/

?>